= Crystal Lang Explorations
Bill Tihen - using Crystal 0.32.1
Version 0.0.1
:sectnums:
:toc:
:toclevels: 4
:toc-title: Contents

:description: Exploring Crystal's Features
:source-highlighter: prettify
:keywords: Crystal Language
:imagesdir: ./images

*link:index.html[Index]*

Exploring & Learning Crystal Language via topics that are interesting _(at least to me)_ and hopefully augment it's documentation.  This will be light on theory (lots of that available) and focus on exploring the code and how it works.

Resources that helped are:

* Crystal Lang API Docs - https://crystal-lang.org/api/0.32.1/
* Crystal Lang GitBook - https://crystal-lang.org/reference/guides
* I also found the *Crystal Lang Gitter - https://gitter.im/crystal-lang/crystal* folks instrumental in helping me better undstand and putting these ideas into a context where I could write code that works.

WARNING: This code does not focus on best practices, security or production ready code.  The code is just good enough to demonstrate what is happening.

== Installation

Please see https://crystal-lang.org/install/

== Using Crystal CLI

* get cli help
```
crystal -h
```

* generate a new app:
```
crystal init app project_name
cd project_name
```

* compile and run (while developing):
```
crystal run src/code.cr
```

* compile to executable and run:
```
crystal build src/file.cr
./file
```

* compile and optimize build (for release into the wild):
```
crystal build --release src/file.cr -o new_name
./new_name
```

* compile with Parallelism enabled (experimental) - https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html
```
crystal build -Dpreview_mt code.cr -o code
$ ./code                   # defaul is 4 workers
$ CRYSTAL_WORKERS=2 ./code # uses two CPUS
$ CRYSTAL_WORKERS=4 ./code # same as default
```

* compile and run (all) specs:
```
crystal spec
```

* build docs from code comments
```
crystal docs
```

== link:concurrency.html[Concurrency]

== link:channels.html[Channels]

== link:channel_callbacks.html[Channel Callbacks]

== link:parallelism.html[Parallelism]

== Macros


*link:index.html[Index]*
