= Crystal Lang Parallelism
Bill Tihen - using Crystal 0.32.1
Version 0.0.1
:sectnums:
:toc:
:toclevels: 4
:toc-title: Contents

:description: Exploring Crystal's Features
:source-highlighter: prettify
:keywords: Crystal Language
:imagesdir: ./images


*link:index.html[Index]*


Exploring & Learning Crystal Language via topics that are interesting _(at least to me)_ and hopefully augment it's documentation.  This will be light on theory (lots of that available) and focus on exploring the code and how it works.

Resources that helped are:
* Crystal Lang API Docs - https://crystal-lang.org/api/0.32.1/Fiber.html
* Crystal Lang GitBook - https://crystal-lang.org/reference/guides/concurrency.html
I also found the *Crystal Lang Gitter - https://gitter.im/crystal-lang/crystal* folks instrumental in helping me better undstand and putting these ideas into a context where I could write code that works.

WARNING: This code does not focus on best practices, security or production ready code.  The code is just good enough to demonstrate what is happening.

== https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html[Parallelism]

NOTE: Compiling for Parallelism is EXPERIMENTAL


To compile and run with parallelism enabled use: 
```
crystal build -Dpreview_mt code.cr -o code
$ ./code                   # defaul is 4 workers
$ CRYSTAL_WORKERS=2 ./code # uses two CPUS
$ CRYSTAL_WORKERS=4 ./code # same as default
```


*link:index.html[Index]*
